### ISSUE TITLE
strings from mgd files that are enclosed in {ts}

### ISSUE THREAD

**Issue by jmcclelland** [civicrm/civistrings#11]
`civistrings` does not seem to find translations strings in my .mgd.php file that are enclosed in {ts}{/ts}.

I think I'm using best practices but also this feels a bit like a corner case.

In short, I have a mgd.php file that includes a message template. So, I suspect civistrings thinks it's a php file so looks for `ts()`. But, since I have message template code, I need it to also find '{ts}{/ts}'.

Should civistrings be patched to handle this situation or is there a different work around I should be using?

**Comment by demeritcowboy** [comment]
I don't know if it's a bug or not but a quick workaround that comes to mind is in mgd.php instead of

`myfield => 'Message template string that {ts}includes ts{/ts}.'`

do

`myfield => file_get_contents(__DIR__ . '../templates/path/to/msg.tpl')`

Then your tpl is a tpl. And also avoids some possible quote-hell.

**Comment by seamuslee001** [comment]
@jmcclelland I think looking at this https://github.com/civicrm/civistrings/blob/75f490ca47fe2fad3eca2ca12899371c8d758e88/src/Command/ExtractCommand.php#L184 it would be parsing it as standard php as you say expecting E::ts() or ts() style, is there a reason why you are using the smarty style `{ts}{/ts}` in your managed entity

**Comment by jmcclelland** [comment]
Hi all - Thanks so much for the feedback! @seamuslee001 - I'm using smarty style in my managed entity because I'm managing a message template entity. And @demeritcowboy's suggestion is perfect. I think that generally makes those templates a lot easier to manage moving forward so it's a better way to go even if it wasn't for this particular problem.
