### ISSUE TITLE
php parser doesn't handle newer php syntax for lists

### ISSUE THREAD

**Issue by demeritcowboy** [civicrm/civistrings#7]
For example it will fail on uk.co.compucorp.civicase for things [like this](https://github.com/compucorp/uk.co.compucorp.civicase/blob/46fa1c3c4c15a7311c3722fa27b51ee9802e8143/CRM/Civicase/APIHelpers/CaseDetails.php#L98-L105):

```
list(
      'query' => $roleQuery,
      'where' => $roleWhere
    ) = self::getRoleQuery([
      'can_be_client' => TRUE,
      'all_case_roles_selected' => TRUE,
      'contact' => $params['contact_involved'],
    ]);
```

`Syntax error, unexpected T_CONSTANT_ENCAPSED_STRING, expecting ',' or ')' on line 99`

And also just using `[]` instead of `list` such as [this](https://github.com/compucorp/uk.co.compucorp.civicase/blob/46fa1c3c4c15a7311c3722fa27b51ee9802e8143/CRM/Civicase/Service/CaseCategoryFromUrl.php#L204):

`[$entityName, $action, $params] = $entity;`

FYI @mlutfy this is why it failed during the presentation today.

Perhaps the parser just needs to be updated to the latest version?

**Comment by demeritcowboy** [comment]
Added PR https://github.com/civicrm/civistrings/pull/8

So note civistrings is breaking in core too for things like https://github.com/civicrm/civicrm-core/blob/9a66ac8d272ee7add293ac139c50a1ce094a2948/CRM/Contact/Form/Task.php#L91

`[$form->_task, $title] = CRM_Contact_Task::getTaskAndTitleByClass(get_class($form));`

**Comment by mlutfy** [comment]
PR merged, thank you!

**Comment by demeritcowboy** [comment]
Thanks!
