### ISSUE TITLE
Getting traceback from php-parser - possibly php8.1 issue

### ISSUE THREAD

**Issue by jmcclelland** [civicrm/civistrings#9]
When I run `civistrings` on a file that has a function that accepts a value by reference (`&$var`) I get this error:

```
Error: Warning: Undefined array key 403 in /home/jamie/projects/ptp/repos/civistrings/vendor/nikic/php-p  arser/lib/PhpParser/Lexer.php on line 329
  PHP Fatal error:  Uncaught TypeError: PhpParser\Lexer::getNextToken(): Return value must be of type int,   null returned in /home/jamie/projects/ptp/repos/civistrings/vendor/nikic/php-parser/lib/PhpParser/Lexer  .php:369
```

I experimentally bumped the version of `php-parser` from 4.10.2 to the latest 4.13.2 and it resolved the issue.

**Comment by seamuslee001** [comment]
@mlutfy @demeritcowboy FYI ^

**Comment by demeritcowboy** [comment]
I can reproduce and it does seem 8.1 related (https://github.com/nikic/PHP-Parser/blob/a6e34665fd6a2bcefc924cb5fd73788767ae510e/CHANGELOG.md#fixed-3).

I'll try out the updated parser.

**Comment by demeritcowboy** [comment]
Have added https://github.com/civicrm/civistrings/pull/10

**Comment by totten** [comment]
New PHAR includes #10.

See also: https://github.com/civicrm/civicrm-buildkit/commit/10dc000d35ca6d816aa3a6811c1a71d015e444ee
